# Generated by Django 3.2.4 on 2021-06-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
